#!/bin/bash

PREFIX=/home/foo/fun/twitch
TOKEN=$PREFIX/token
JSON=$PREFIX/foo.json
STREAMS=$PREFIX/streams.txt

curl -s -H 'Accept: application/vnd.twitchtv.v3+json' -H "Authorization: OAuth $(cat $TOKEN)" \
    -X GET https://api.twitch.tv/kraken/streams/followed?stream_type=live,offset=5 \
    -o $JSON

IFS_=$IFS
IFS=$(echo -en \n\b)
IFS=$'\n'

name=($(jq '.streams[].channel.name' $JSON))
display_name=($(jq '.streams[].channel.display_name' $JSON))
status=($(jq '.streams[].channel.status' $JSON))
game=($(jq '.streams[].channel.game' $JSON))

for ii in $(seq 0 $(( ${#name[@]} - 1 ))); do
    echo -e $ii:"\t"${name[$ii]}"\t"${game[$ii]}"\t"${status[$ii]}"\t"${name[$ii]}
done | column -t -s \" | sed 's/\t/  /g' > $STREAMS

selected=$(cat $STREAMS | dmenu -l 20 | awk 'NF>1 {printf $NF}')
if [[ $selected == '' ]]; then 
    exit 22
fi
IFS=$IFS_

twitch_watch $selected
