#!/bin/bash

RUN_DIR="/tmp/dtwitch/"
TABBED_PID=$RUN_DIR"/tabbed.pid"
TABBED_XID=$RUN_DIR"/tabbed.xid"
OUTPUT=$RUN_DIR"/livestreamer_out"

STREAM_NAME="epicenter_en1" # just random online chanel for debug
STREAM_NAME=$1

if [[ $STREAM_NAME == "" ]]; then
    echo NOTHING?!+ 
    exit 42
else
    URL="https://www.twitch.tv/"$STREAM_NAME 
    CHAT_URL="https://www.twitch.tv/"$STREAM_NAME"/chat?popout="
fi

if [ ! -d "$RUN_DIR" ]; then
    ( mkdir $RUN_DIR ) || { 
        echo "Can't create dir $RUN_DIR"
        exit 12
    }
fi


# Open stream
( livestreamer $URL > $OUTPUT ) || {
    ERROR=$?
    echo livestreamer failed
    echo livestreamer $URL
    exit $ERROR
}

QUAL="best"
OUT=$(cat $OUTPUT | grep "Available streams")
( echo $OUT | grep best) || {
    QUAL=$(echo $OUT | sed 's/.*://;s/,//g;s/ /\n/g;s/audio//' | sort -h | tail -n 1)
}

# Open chat
PID=$(cat $TABBED_PID 2>/dev/null)
XID=$(cat $TABBED_XID 2>/dev/null)

ps -p $PID 2>&1 | grep '[t]'abbed > /dev/null 2>&1
TABBED_FOUND=$?
if [[ $TABBED_FOUND != 0 ]] || [[ $XID == "" ]] ; then 
    echo "Create new tabbed"
    if [[ $TABBED_FOUND != 0 ]]; then
        echo 'tabbed not found'
    fi 
    if [[ $XID == "" ]]; then 
        echo "XID is empty, why?!+" 
    fi 
    
    tabbed -n "twitch chat" -c  > $TABBED_XID &
    PID=$!
    echo $PID > $TABBED_PID
    XID=""; 
    for ii in 1 2 3 4 5 6 7 8 9; do 
        XID=$(cat $TABBED_XID 2>/dev/null)
        if [[ $XID != "" ]]; then
            break
        fi 
        sleep .1s 
    done 
fi 

echo xid: $XID
echo pid: $PID
echo 'surf -e $XID -l "'$STREAM_NAME'" "'$CHAT_URL'" > /dev/null 2>&1 '
surf -e $XID -l "$STREAM_NAME" $CHAT_URL > /dev/null 2>&1 & 
CHAT_PID=$!
echo $CHAT_PID

# firefox --new-window "https://www.twitch.tv/"$STREAM_NAME"/chat?popout=" &
echo livestreamer $URL $QUAL
livestreamer $URL $QUAL
kill -s 15 $CHAT_PID

